import React from "react";
import { useLocation, useNavigate } from "react-router-dom";
import {
  ShieldCheck,
  User,
  FileText,
  BadgeIndianRupee,
  CalendarDays,
  Receipt,
  Wallet,
  CheckCircle2,
  Download,
} from "lucide-react";

import { jsPDF } from "jspdf";
import logo from "../../assets/images/logo.png";

const PolicySuccessPage = () => {
  const location = useLocation();
  const navigate = useNavigate();

  const proposal = location.state?.proposal || {};
  /*
|--------------------------------------------------------------------------
| RENEWAL DATA
|--------------------------------------------------------------------------
*/

  const renewal = location.state?.renewal || false;

  const renewalData = location.state?.renewalData || null;

  // =========================
  // FORMATTERS
  // =========================

  const formatDate = (date) => {
    if (!date) return "N/A";

    return new Date(date).toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  };

  const formatCurrency = (amount) => {
    return `₹${Number(amount || 0).toLocaleString("en-IN")}`;
  };

  // =========================
  // DOWNLOAD RECEIPT PDF
  // =========================

  const downloadReceipt = () => {
    const doc = new jsPDF();

    // =====================
    // HEADER
    // =====================

    doc.setFillColor(7, 20, 55);
    doc.rect(0, 0, 210, 38, "F");

    doc.addImage(logo, "PNG", 14, 8, 28, 18);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("PAYMENT RECEIPT", 110, 22);

    // =====================
    // BODY
    // =====================

    doc.setTextColor(20, 20, 20);

    doc.setDrawColor(220);
    doc.roundedRect(14, 48, 182, 120, 4, 4);

    const startY = 62;
    const gap = 14;

    const rows = [
      ["Customer Name", proposal.full_name],
      ["Application Number", proposal.application_number],
      ["Policy Number", proposal.policy_number],
      ["Transaction ID", proposal.transaction_id],
      ["Insurance Type", proposal.category],
      [
        "Premium Paid",
        `Rs. ${Number(proposal.premium_amount).toLocaleString("en-IN")}`,
      ],
      ["Payment Status", proposal.payment_status],
      ["Payment Date", formatDate(proposal.payment_date)],
    ];

    rows.forEach((row, index) => {
      const y = startY + index * gap;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text(`${row[0]} :`, 24, y);

      doc.setFont("times", "normal");
      doc.text(`${row[1] || "N/A"}`, 85, y);
    });

    // =====================
    // FOOTER
    // =====================

    doc.setFillColor(245, 247, 250);
    doc.rect(0, 270, 210, 27, "F");

    doc.setFontSize(10);
    doc.setTextColor(100);

    doc.text("This is a system generated receipt by SPAY Insurance.", 14, 286);

    doc.save(`Receipt_${proposal.policy_number}.pdf`);
  };

  // =========================
  // DOWNLOAD POLICY PDF
  // =========================

  const downloadPolicy = () => {
    const doc = new jsPDF();

    // =====================
    // HEADER
    // =====================

    doc.setFillColor(41, 82, 255);
    doc.rect(0, 0, 210, 40, "F");

    doc.addImage(logo, "PNG", 14, 8, 28, 18);

    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");

    doc.text("INSURANCE POLICY", 95, 23);

    // =====================
    // TITLE
    // =====================

    doc.setTextColor(20);

    doc.setFontSize(18);
    doc.text("Policy Holder Details", 14, 58);

    // =====================
    // CARD
    // =====================

    doc.setDrawColor(220);
    doc.roundedRect(14, 66, 182, 165, 4, 4);

    const startY = 82;
    const gap = 14;

    const rows = [
      ["Customer Name", proposal.full_name],
      ["Policy Number", proposal.policy_number],
      ["Application Number", proposal.application_number],
      ["Insurance Type", proposal.category],
      [
        "Premium Amount",
        `Rs. ${Number(proposal.premium_amount).toLocaleString("en-IN")}`,
      ],
      ["Policy Tenure", `${proposal.tenure} Year`],
      ["Policy Start Date", formatDate(proposal.policy_start_date)],
      ["Policy End Date", formatDate(proposal.policy_end_date)],
      ["Payment Status", proposal.payment_status],
      ["Policy Status", proposal.policy_status],
      ["Transaction ID", proposal.transaction_id],
    ];

    rows.forEach((row, index) => {
      const y = startY + index * gap;

      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);

      doc.text(`${row[0]} :`, 24, y);

      doc.setFont("times", "normal");

      doc.text(`${row[1] || "N/A"}`, 88, y);
    });

    // =====================
    // TERMS
    // =====================

    doc.setFontSize(11);
    doc.setTextColor(120);

    doc.text(
      "This policy document is digitally generated by SPAY Insurance.",
      14,
      250,
    );

    doc.text(
      "Please keep this document safe for future claims and renewals.",
      14,
      258,
    );

    // =====================
    // FOOTER
    // =====================

    doc.setFillColor(245, 247, 250);
    doc.rect(0, 275, 210, 22, "F");

    doc.setFontSize(10);

    doc.text(
      "SPAY Insurance Pvt Ltd • support@spay.live • www.spay.live",
      14,
      288,
    );

    doc.save(`Policy_${proposal.policy_number}.pdf`);
  };

  // =========================
  // INFO CARD
  // =========================

  const InfoCard = ({ icon, label, value }) => (
    <div className="rounded-xl border border-slate-200 bg-white p-4 transition-all hover:shadow-sm">
      <div className="flex items-start gap-3">
        <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600">
          {icon}
        </div>

        <div className="min-w-0 flex-1">
          <p className="text-xs font-medium text-slate-500">{label}</p>

          <h3 className="mt-1 break-words text-sm font-semibold text-slate-900">
            {value}
          </h3>
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#f3f6fb] py-10 px-5">
      <div className="max-w-[1400px] mx-auto">
        {/* HEADER */}

        <div className="bg-white border border-slate-200 rounded-[28px] p-6 flex items-center justify-between gap-5 mb-7">
          <div className="flex items-center gap-5">
            <img src={logo} alt="logo" className="h-16 object-contain" />

            <div>
              <h1 className="text-[48px] font-black text-[#071437] leading-none">
                {renewal
                  ? "Policy Renewed Successfully"
                  : "Policy Generated Successfully"}
              </h1>

              <p className="text-slate-500 mt-3 text-[16px]">
                {renewal
                  ? "Your insurance policy has been renewed and extended successfully."
                  : "Your insurance policy is active and verified successfully."}
              </p>
            </div>
          </div>
          {renewal && (
            <div className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#EFF6FF] px-4 py-2">
              <CheckCircle2 className="h-4 w-4 text-[#2563EB]" />

              <span className="text-[12px] font-semibold text-[#2563EB]">
                Renewal Completed
              </span>
            </div>
          )}
          <div className="flex items-center gap-4">
            <button
              onClick={downloadReceipt}
              className="h-[56px] px-7 rounded-2xl bg-[#071437] text-white font-semibold flex items-center gap-3 hover:scale-[1.02] transition-all"
            >
              <Receipt className="h-5 w-5" />
              Download Receipt
            </button>

            <button
              onClick={downloadPolicy}
              className="h-[56px] px-7 rounded-2xl bg-[#2952ff] text-white font-semibold flex items-center gap-3 hover:scale-[1.02] transition-all"
            >
              <Download className="h-5 w-5" />
              Download Policy
            </button>
          </div>
        </div>

        {/* MAIN */}

        <div className="grid grid-cols-12 gap-7">
          {/* LEFT */}

          <div className="col-span-8">
            <div className="bg-white border border-slate-200 rounded-[28px] p-6">
              <div className="flex items-center justify-between mb-7">
                <h2 className="text-[42px] font-black text-[#071437]">
                  Policy Details
                </h2>

                <div className="px-5 py-2 rounded-full bg-green-100 text-green-700 text-[14px] font-semibold">
                  {renewal ? "Renewed Policy" : "Active Policy"}
                </div>
              </div>

              <div className="grid grid-cols-2 gap-5">
                <InfoCard
                  icon={<User className="h-6 w-6" />}
                  label="Customer Name"
                  value={proposal.full_name || "N/A"}
                />

                <InfoCard
                  icon={<ShieldCheck className="h-6 w-6" />}
                  label="Insurance Type"
                  value={proposal.category || "N/A"}
                />

                <InfoCard
                  icon={<FileText className="h-6 w-6" />}
                  label="Policy Number"
                  value={proposal.policy_number || "N/A"}
                />

                <InfoCard
                  icon={<Receipt className="h-6 w-6" />}
                  label="Application Number"
                  value={proposal.application_number || "N/A"}
                />

                <InfoCard
                  icon={<BadgeIndianRupee className="h-6 w-6" />}
                  label="Premium Paid"
                  value={formatCurrency(proposal.premium_amount)}
                />

                <InfoCard
                  icon={<CalendarDays className="h-6 w-6" />}
                  label="Policy Duration"
                  value={`${proposal.tenure || 0} Year`}
                />

                <InfoCard
                  icon={<CalendarDays className="h-6 w-6" />}
                  label="Start Date"
                  value={formatDate(proposal.policy_start_date)}
                />

                <InfoCard
                  icon={<CalendarDays className="h-6 w-6" />}
                  label="End Date"
                  value={formatDate(proposal.policy_end_date)}
                />

                <InfoCard
                  icon={<Wallet className="h-6 w-6" />}
                  label="Transaction ID"
                  value={proposal.transaction_id || "N/A"}
                />

                <InfoCard
                  icon={<CheckCircle2 className="h-6 w-6" />}
                  label="Payment Status"
                  value={proposal.payment_status || "N/A"}
                />
              </div>
            </div>
            {renewal && (
              <div className="bg-gradient-to-r from-[#EFF6FF] to-[#F8FBFF] border border-[#DBEAFE] rounded-[28px] p-6 mb-7">
                <div className="flex items-center justify-between">
                  <div>
                    <h2 className="text-[34px] font-black text-[#071437]">
                      Renewal Summary
                    </h2>

                    <p className="mt-2 text-[15px] text-slate-500">
                      Your previous policy has been renewed successfully.
                    </p>
                  </div>

                  <div className="rounded-full bg-green-100 px-4 py-2 text-[13px] font-semibold text-green-700">
                    Renewal Successful
                  </div>
                </div>

                <div className="mt-6 grid grid-cols-2 gap-5">
                  <InfoCard
                    icon={<FileText className="h-6 w-6" />}
                    label="Previous Policy Number"
                    value={renewalData?.policy_number || "N/A"}
                  />

                  <InfoCard
                    icon={<CalendarDays className="h-6 w-6" />}
                    label="Previous Expiry Date"
                    value={formatDate(renewalData?.policy_end_date)}
                  />

                  <InfoCard
                    icon={<ShieldCheck className="h-6 w-6" />}
                    label="Renewed Policy Number"
                    value={proposal?.policy_number || "N/A"}
                  />

                  <InfoCard
                    icon={<CalendarDays className="h-6 w-6" />}
                    label="New Expiry Date"
                    value={formatDate(proposal?.policy_end_date)}
                  />
                </div>
              </div>
            )}
            {/* PAYMENT SUMMARY */}

            <div className="bg-white border border-slate-200 rounded-[28px] p-6 mt-7">
              <h2 className="text-[36px] font-black text-[#071437] mb-7">
                Payment Summary
              </h2>

              <div className="space-y-5">
                <div className="flex justify-between text-[18px]">
                  <span className="text-slate-500">Premium Amount</span>

                  <span className="font-bold text-[#071437]">
                    {formatCurrency(proposal.premium_amount)}
                  </span>
                </div>

                <div className="flex justify-between text-[18px]">
                  <span className="text-slate-500">GST (18%)</span>

                  <span className="font-bold text-[#071437]">
                    ₹
                    {(
                      Number(proposal.premium_amount || 0) * 0.18
                    ).toLocaleString("en-IN")}
                  </span>
                </div>

                <div className="border-t pt-5 flex justify-between">
                  <span className="text-[28px] font-black text-[#071437]">
                    Total Paid
                  </span>

                  <span className="text-[32px] font-black text-green-600">
                    {formatCurrency(proposal.premium_amount)}
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* RIGHT */}

          <div className="col-span-4 space-y-6">
            <div className="bg-[#071437] rounded-[28px] p-7 text-white">
              <div className="h-16 w-16 rounded-3xl bg-white/10 flex items-center justify-center mb-7">
                <ShieldCheck className="h-8 w-8 text-[#4ade80]" />
              </div>

              <h2 className="text-[42px] font-black mb-4 leading-tight">
                {renewal ? "Policy Renewed" : "Policy Generated"}
              </h2>

              <p className="text-white/80 text-[18px] leading-[32px]">
                {renewal
                  ? "Your insurance policy renewal has been completed successfully and your coverage has been extended."
                  : "Your insurance policy has been generated successfully and is now active."}
              </p>
            </div>

            <div className="bg-white border border-slate-200 rounded-[28px] p-6">
              <h2 className="text-[36px] font-black text-[#071437] mb-6">
                Support Information
              </h2>

              <div className="space-y-6">
                <div>
                  <p className="text-slate-500 text-[15px] mb-1">
                    Support Email
                  </p>

                  <h3 className="text-[18px] font-bold text-[#071437]">
                    support@spay.live
                  </h3>
                </div>

                <div>
                  <p className="text-slate-500 text-[15px] mb-1">
                    Customer Care
                  </p>

                  <h3 className="text-[18px] font-bold text-[#071437]">
                    +91 9876543210
                  </h3>
                </div>

                <div>
                  <p className="text-slate-500 text-[15px] mb-1">
                    Office Address
                  </p>

                  <h3 className="text-[18px] font-bold text-[#071437] leading-[32px]">
                    SPAY Insurance Pvt Ltd, Mumbai, India
                  </h3>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PolicySuccessPage;
