import React, { useRef } from "react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import {
  ShieldCheck,
  User,
  FileText,
  BadgeIndianRupee,
  CalendarDays,
  Receipt,
  Wallet,
  CheckCircle2,
} from "lucide-react";

const PolicyPDF = ({ policyData }) => {
  const pdfRef = useRef();

  const generatePDF = async () => {
    const input = pdfRef.current;

    const canvas = await html2canvas(input, {
      scale: 2,
      useCORS: true,
    });

    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");

    const pdfWidth = pdf.internal.pageSize.getWidth();

    const pdfHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = pdfWidth;

    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;

    let position = 0;

    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);

    heightLeft -= pdfHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;

      pdf.addPage();

      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);

      heightLeft -= pdfHeight;
    }

    pdf.save(
      `${policyData?.policy_number || "insurance-policy"}.pdf`
    );
  };

  const details = [
    {
      label: "Customer Name",
      value: policyData?.full_name || "N/A",
      icon: <User className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Policy Number",
      value: policyData?.policy_number || "Pending",
      icon: <FileText className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Application Number",
      value: policyData?.application_number || "N/A",
      icon: <Receipt className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Insurance Type",
      value:
        policyData?.category?.charAt(0).toUpperCase() +
          policyData?.category?.slice(1) +
          " Insurance" || "N/A",
      icon: <ShieldCheck className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Premium Paid",
      value: policyData?.formatted_premium || "₹0",
      icon: (
        <BadgeIndianRupee className="h-5 w-5 text-indigo-600" />
      ),
    },

    {
      label: "Tenure",
      value: `${policyData?.tenure || 1} Year`,
      icon: <CalendarDays className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Policy Start Date",
      value: policyData?.policy_start_date
        ? new Date(
            policyData.policy_start_date
          ).toLocaleDateString("en-IN")
        : "N/A",
      icon: <CalendarDays className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Policy End Date",
      value: policyData?.policy_end_date
        ? new Date(
            policyData.policy_end_date
          ).toLocaleDateString("en-IN")
        : "N/A",
      icon: <CalendarDays className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Transaction ID",
      value: policyData?.transaction_id || "N/A",
      icon: <Wallet className="h-5 w-5 text-indigo-600" />,
    },

    {
      label: "Payment Status",
      value: policyData?.payment_status || "Pending",
      icon: <CheckCircle2 className="h-5 w-5 text-green-600" />,
    },

    {
      label: "Policy Status",
      value: policyData?.policy_status || "Pending",
      icon: <ShieldCheck className="h-5 w-5 text-emerald-600" />,
    },

    {
      label: "Payment Date",
      value: policyData?.payment_date
        ? new Date(policyData.payment_date).toLocaleString("en-IN")
        : "N/A",
      icon: <CalendarDays className="h-5 w-5 text-indigo-600" />,
    },
  ];

  return (
    <div>
      {/* DOWNLOAD BUTTON */}

      <button
        onClick={generatePDF}
        className="bg-[#081028] text-white px-6 py-3 rounded-2xl font-semibold hover:scale-[1.02] transition-all"
      >
        Download Policy PDF
      </button>

      {/* PDF CONTENT */}

      <div
        ref={pdfRef}
        className="bg-[#f4f7fb] p-10 mt-6 rounded-3xl"
      >
        {/* HEADER */}

        <div className="bg-[#081028] rounded-[30px] p-8 text-white relative overflow-hidden">
          <div className="absolute right-[-50px] top-[-50px] h-[180px] w-[180px] rounded-full bg-indigo-500/20"></div>

          <div className="flex items-start justify-between relative z-10">
            <div>
              <img
                src="/logo.png"
                alt="logo"
                className="h-12 mb-6"
              />

              <h1 className="text-4xl font-black">
                Policy Certificate
              </h1>

              <p className="text-slate-300 mt-3 text-[15px]">
                Official insurance policy document generated by
                SPAY Insurance.
              </p>
            </div>

            <div className="bg-white/10 border border-white/10 rounded-3xl p-5 min-w-[260px]">
              <div className="space-y-4">
                <div>
                  <p className="text-slate-300 text-sm">
                    Policy Number
                  </p>

                  <h3 className="font-black text-xl break-all">
                    {policyData?.policy_number || "Pending"}
                  </h3>
                </div>

                <div>
                  <p className="text-slate-300 text-sm">
                    Application Number
                  </p>

                  <h3 className="font-black text-lg break-all">
                    {policyData?.application_number || "N/A"}
                  </h3>
                </div>

                <div className="inline-flex items-center gap-2 bg-emerald-500/20 border border-emerald-400/20 rounded-full px-4 py-2 mt-2">
                  <CheckCircle2 className="h-4 w-4 text-emerald-400" />

                  <span className="text-sm font-semibold text-emerald-300">
                    Active Policy
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* CUSTOMER DETAILS */}

        <div className="bg-white rounded-[30px] p-8 mt-8 border border-slate-200">
          <div className="flex items-center gap-3 mb-8">
            <div className="h-14 w-14 rounded-2xl bg-indigo-50 flex items-center justify-center">
              <ShieldCheck className="h-7 w-7 text-indigo-600" />
            </div>

            <div>
              <h2 className="text-3xl font-black text-[#081028]">
                Policy Details
              </h2>

              <p className="text-slate-500 mt-1">
                Complete insurance summary & customer details
              </p>
            </div>
          </div>

          {/* DETAILS GRID */}

          <div className="grid grid-cols-2 gap-5">
            {details.map((item, index) => (
              <div
                key={index}
                className="border border-slate-200 rounded-3xl p-5"
              >
                <div className="flex items-start gap-4">
                  <div className="h-14 w-14 rounded-2xl bg-indigo-50 flex items-center justify-center shrink-0">
                    {item.icon}
                  </div>

                  <div>
                    <p className="text-sm text-slate-500 mb-1">
                      {item.label}
                    </p>

                    <h3 className="text-[20px] font-black text-[#081028] break-all">
                      {item.value}
                    </h3>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* PAYMENT SUMMARY */}

        <div className="grid grid-cols-2 gap-6 mt-8">
          <div className="bg-white rounded-[30px] border border-slate-200 p-7">
            <h2 className="text-2xl font-black text-[#081028] mb-6">
              Payment Summary
            </h2>

            <div className="space-y-5">
              <div className="flex items-center justify-between">
                <span className="text-slate-500">
                  Premium Amount
                </span>

                <span className="font-bold text-[#081028]">
                  {policyData?.formatted_premium || "₹0"}
                </span>
              </div>

              <div className="flex items-center justify-between">
                <span className="text-slate-500">
                  GST (18%)
                </span>

                <span className="font-bold text-[#081028]">
                  ₹
                  {(
                    Number(policyData?.premium_amount || 0) * 0.18
                  ).toFixed(0)}
                </span>
              </div>

              <div className="border-t border-dashed border-slate-300 pt-5 flex items-center justify-between">
                <span className="text-xl font-black text-[#081028]">
                  Total Paid
                </span>

                <span className="text-3xl font-black text-emerald-600">
                  ₹
                  {(
                    Number(policyData?.premium_amount || 0) * 1.18
                  ).toFixed(0)}
                </span>
              </div>
            </div>
          </div>

          {/* SUPPORT */}

          <div className="bg-[#081028] rounded-[30px] p-7 text-white">
            <h2 className="text-2xl font-black mb-6">
              Support Information
            </h2>

            <div className="space-y-5">
              <div>
                <p className="text-slate-400 text-sm">
                  Support Email
                </p>

                <h3 className="font-semibold text-lg">
                  support@spay.live
                </h3>
              </div>

              <div>
                <p className="text-slate-400 text-sm">
                  Customer Care
                </p>

                <h3 className="font-semibold text-lg">
                  +91 9876543210
                </h3>
              </div>

              <div>
                <p className="text-slate-400 text-sm">
                  Office Address
                </p>

                <h3 className="font-semibold text-lg leading-8">
                  SPAY Insurance Pvt Ltd,
                  <br />
                  Mumbai, India
                </h3>
              </div>
            </div>
          </div>
        </div>

        {/* TERMS */}

        <div className="bg-orange-50 border border-orange-100 rounded-[30px] p-7 mt-8">
          <h2 className="text-2xl font-black text-orange-900 mb-5">
            Terms & Conditions
          </h2>

          <div className="space-y-3 text-[15px] text-orange-800 leading-8">
            <p>
              • This document is digitally generated and does not
              require physical signature.
            </p>

            <p>
              • Please save your Policy Number and Application
              Number securely.
            </p>

            <p>
              • Renewal reminders will be sent before policy expiry.
            </p>

            <p>
              • Claims are subject to insurer verification and
              policy terms.
            </p>

            <p>
              • Contact support for claim assistance, renewals,
              and policy updates.
            </p>
          </div>
        </div>

        {/* FOOTER */}

        <div className="text-center mt-10">
          <p className="text-slate-500 text-sm">
            © {new Date().getFullYear()} SPAY Insurance.
            All rights reserved.
          </p>

          <p className="text-slate-400 text-xs mt-2">
            This policy document is system generated.
          </p>
        </div>
      </div>
    </div>
  );
};

export default PolicyPDF;