import React, { useRef } from "react";

import html2canvas from "html2canvas";

import jsPDF from "jspdf";

import {
  Download,
  Receipt,
  Wallet,
  CheckCircle2,
  CalendarDays,
  User,
  ShieldCheck,
  BadgeIndianRupee,
  ArrowRight,
} from "lucide-react";

const ReceiptPDF = ({ policyData }) => {
  const receiptRef = useRef();

  /*
  |--------------------------------------------------------------------------
  | GENERATE RECEIPT PDF
  |--------------------------------------------------------------------------
  */

  const generateReceiptPDF = async () => {
    const input = receiptRef.current;

    const canvas = await html2canvas(input, {
      scale: 2,
      useCORS: true,
    });

    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");

    const pdfWidth = pdf.internal.pageSize.getWidth();

    const pdfHeight = pdf.internal.pageSize.getHeight();

    const imgWidth = pdfWidth;

    const imgHeight =
      (canvas.height * imgWidth) / canvas.width;

    let heightLeft = imgHeight;

    let position = 0;

    pdf.addImage(
      imgData,
      "PNG",
      0,
      position,
      imgWidth,
      imgHeight
    );

    heightLeft -= pdfHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;

      pdf.addPage();

      pdf.addImage(
        imgData,
        "PNG",
        0,
        position,
        imgWidth,
        imgHeight
      );

      heightLeft -= pdfHeight;
    }

    pdf.save(
      `Receipt-${policyData?.policy_number || "Insurance"}.pdf`
    );
  };

  /*
  |--------------------------------------------------------------------------
  | CALCULATIONS
  |--------------------------------------------------------------------------
  */

  const premium = Number(
    policyData?.premium_amount || 0
  );

  const gst = Math.round((premium * 18) / 100);

  const total = premium + gst;

  /*
  |--------------------------------------------------------------------------
  | FORMATTED DATES
  |--------------------------------------------------------------------------
  */

  const paymentDate = policyData?.payment_date
    ? new Date(
        policyData.payment_date
      ).toLocaleString("en-IN")
    : "N/A";

  /*
  |--------------------------------------------------------------------------
  | UI
  |--------------------------------------------------------------------------
  */

  return (
    <div>
      {/* DOWNLOAD BUTTON */}

      <button
        onClick={generateReceiptPDF}
        className="w-full flex items-center justify-between bg-white/10 hover:bg-white/20 transition-all rounded-2xl px-5 py-4 text-white"
      >
        <div className="flex items-center gap-3">
          <Download className="h-5 w-5" />

          <div className="text-left">
            <p className="font-semibold text-sm">
              Download Receipt
            </p>

            <p className="text-xs text-slate-300">
              Payment invoice PDF
            </p>
          </div>
        </div>

        <ArrowRight className="h-5 w-5" />
      </button>

      {/* PDF CONTENT */}

      <div
        ref={receiptRef}
        className="bg-[#f4f7fb] p-10 mt-6 rounded-[30px]"
      >
        {/* HEADER */}

        <div className="bg-[#081028] rounded-[30px] p-8 text-white relative overflow-hidden">
          <div className="absolute right-[-50px] top-[-50px] h-[180px] w-[180px] rounded-full bg-indigo-500/20"></div>

          <div className="relative z-10 flex items-start justify-between">
            {/* LEFT */}

            <div>
              <img
                src="/logo.png"
                alt="logo"
                className="h-12 mb-6"
              />

              <h1 className="text-4xl font-black">
                Payment Receipt
              </h1>

              <p className="mt-3 text-[15px] text-slate-300">
                Official payment invoice generated by
                SPAY Insurance.
              </p>
            </div>

            {/* RIGHT */}

            <div className="bg-white/10 border border-white/10 rounded-3xl p-5 min-w-[260px]">
              <div className="space-y-4">
                <div>
                  <p className="text-sm text-slate-300">
                    Transaction ID
                  </p>

                  <h3 className="text-lg font-black break-all">
                    {policyData?.transaction_id ||
                      "N/A"}
                  </h3>
                </div>

                <div>
                  <p className="text-sm text-slate-300">
                    Payment Status
                  </p>

                  <div className="inline-flex items-center gap-2 bg-emerald-500/20 border border-emerald-500/20 rounded-full px-4 py-2 mt-2">
                    <CheckCircle2 className="h-4 w-4 text-emerald-400" />

                    <span className="text-sm font-semibold text-emerald-300 capitalize">
                      {policyData?.payment_status ||
                        "Paid"}
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* CUSTOMER + POLICY DETAILS */}

        <div className="grid grid-cols-2 gap-6 mt-8">
          {/* CUSTOMER */}

          <div className="bg-white rounded-[30px] border border-slate-200 p-7">
            <div className="flex items-center gap-3 mb-7">
              <div className="h-14 w-14 rounded-2xl bg-indigo-50 flex items-center justify-center">
                <User className="h-6 w-6 text-indigo-600" />
              </div>

              <div>
                <h2 className="text-2xl font-black text-[#081028]">
                  Customer Details
                </h2>

                <p className="text-slate-500 text-sm mt-1">
                  Insurance holder information
                </p>
              </div>
            </div>

            <div className="space-y-5">
              <div>
                <p className="text-sm text-slate-500">
                  Customer Name
                </p>

                <h3 className="text-xl font-black text-[#081028]">
                  {policyData?.full_name || "N/A"}
                </h3>
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  Email Address
                </p>

                <h3 className="text-lg font-bold text-[#081028] break-all">
                  {policyData?.email || "N/A"}
                </h3>
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  Mobile Number
                </p>

                <h3 className="text-lg font-bold text-[#081028]">
                  {policyData?.mobile || "N/A"}
                </h3>
              </div>
            </div>
          </div>

          {/* POLICY */}

          <div className="bg-white rounded-[30px] border border-slate-200 p-7">
            <div className="flex items-center gap-3 mb-7">
              <div className="h-14 w-14 rounded-2xl bg-indigo-50 flex items-center justify-center">
                <ShieldCheck className="h-6 w-6 text-indigo-600" />
              </div>

              <div>
                <h2 className="text-2xl font-black text-[#081028]">
                  Policy Details
                </h2>

                <p className="text-slate-500 text-sm mt-1">
                  Insurance information
                </p>
              </div>
            </div>

            <div className="space-y-5">
              <div>
                <p className="text-sm text-slate-500">
                  Policy Number
                </p>

                <h3 className="text-lg font-black text-[#081028] break-all">
                  {policyData?.policy_number ||
                    "Pending"}
                </h3>
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  Application Number
                </p>

                <h3 className="text-lg font-bold text-[#081028] break-all">
                  {policyData?.application_number ||
                    "N/A"}
                </h3>
              </div>

              <div>
                <p className="text-sm text-slate-500">
                  Insurance Type
                </p>

                <h3 className="text-lg font-bold text-[#081028] capitalize">
                  {policyData?.category ||
                    "Insurance"}{" "}
                  Insurance
                </h3>
              </div>
            </div>
          </div>
        </div>

        {/* PAYMENT SUMMARY */}

        <div className="bg-white rounded-[30px] border border-slate-200 p-8 mt-8">
          <div className="flex items-center gap-3 mb-8">
            <div className="h-14 w-14 rounded-2xl bg-indigo-50 flex items-center justify-center">
              <Wallet className="h-6 w-6 text-indigo-600" />
            </div>

            <div>
              <h2 className="text-3xl font-black text-[#081028]">
                Payment Summary
              </h2>

              <p className="text-slate-500 mt-1">
                Complete payment breakdown
              </p>
            </div>
          </div>

          <div className="space-y-6">
            {/* PREMIUM */}

            <div className="flex items-center justify-between border-b border-dashed border-slate-200 pb-5">
              <div className="flex items-center gap-3">
                <BadgeIndianRupee className="h-5 w-5 text-indigo-600" />

                <span className="text-lg text-slate-600">
                  Premium Amount
                </span>
              </div>

              <span className="text-2xl font-black text-[#081028]">
                ₹{premium}
              </span>
            </div>

            {/* GST */}

            <div className="flex items-center justify-between border-b border-dashed border-slate-200 pb-5">
              <div className="flex items-center gap-3">
                <Receipt className="h-5 w-5 text-indigo-600" />

                <span className="text-lg text-slate-600">
                  GST (18%)
                </span>
              </div>

              <span className="text-2xl font-black text-[#081028]">
                ₹{gst}
              </span>
            </div>

            {/* TOTAL */}

            <div className="flex items-center justify-between pt-2">
              <div>
                <p className="text-xl font-black text-[#081028]">
                  Total Paid
                </p>

                <p className="text-sm text-slate-500 mt-1">
                  Including all taxes
                </p>
              </div>

              <span className="text-4xl font-black text-emerald-600">
                ₹{total}
              </span>
            </div>
          </div>
        </div>

        {/* FOOTER */}

        <div className="grid grid-cols-2 gap-6 mt-8">
          {/* PAYMENT DATE */}

          <div className="bg-white rounded-[30px] border border-slate-200 p-7">
            <div className="flex items-center gap-3 mb-5">
              <CalendarDays className="h-6 w-6 text-indigo-600" />

              <h2 className="text-2xl font-black text-[#081028]">
                Payment Date
              </h2>
            </div>

            <h3 className="text-xl font-bold text-[#081028]">
              {paymentDate}
            </h3>
          </div>

          {/* STATUS */}

          <div className="bg-[#081028] rounded-[30px] p-7 text-white">
            <div className="flex items-center gap-3 mb-5">
              <CheckCircle2 className="h-6 w-6 text-emerald-400" />

              <h2 className="text-2xl font-black">
                Payment Successful
              </h2>
            </div>

            <p className="text-slate-300 leading-8">
              This receipt confirms that your
              insurance payment has been completed
              successfully and policy has been
              activated.
            </p>
          </div>
        </div>

        {/* TERMS */}

        <div className="bg-orange-50 border border-orange-100 rounded-[30px] p-7 mt-8">
          <h2 className="text-2xl font-black text-orange-900 mb-5">
            Important Note
          </h2>

          <div className="space-y-3 text-[15px] text-orange-800 leading-8">
            <p>
              • This receipt is digitally generated
              and valid without signature.
            </p>

            <p>
              • Please keep this receipt for future
              payment verification.
            </p>

            <p>
              • Contact support for policy updates,
              renewals, and claim assistance.
            </p>
          </div>
        </div>

        {/* FOOTER */}

        <div className="text-center mt-10">
          <p className="text-slate-500 text-sm">
            © {new Date().getFullYear()} SPAY
            Insurance. All rights reserved.
          </p>

          <p className="text-slate-400 text-xs mt-2">
            This receipt document is system
            generated.
          </p>
        </div>
      </div>
    </div>
  );
};

export default ReceiptPDF;